export type State = { state: string; cities: string[] };

export const states: State[] = [
  {
    state: "Ariana",
    cities: [
      "Mnihla",
      "Kalaat Landlous",
      "La Soukra",
      "Raoued",
      "Ariana Ville",
      "Ettadhamen",
      "Sidi Thabet",
    ],
  },
  {
    state: "Beja",
    cities: [
      "Mejez El Bab",
      "Teboursouk",
      "Goubellat",
      "Amdoun",
      "Beja Nord",
      "Thibar",
      "Nefza",
      "Beja Sud",
      "Testour",
    ],
  },
  {
    state: "Ben Arous",
    cities: [
      "Bou Mhel El Bassatine",
      "Nouvelle Medina",
      "Ezzahra",
      "Fouchana",
      "Hammam Chatt",
      "El Mourouj",
      "Rades",
      "Hammam Lif",
      "Mohamadia",
      "Megrine",
      "Ben Arous",
      "Mornag",
    ],
  },
  {
    state: "Bizerte",
    cities: [
      "Ghar El Melh",
      "Menzel Jemil",
      "Ras Jebel",
      "Sejnane",
      "Joumine",
      "Bizerte Sud",
      "El Alia",
      "Menzel Bourguiba",
      "Tinja",
      "Mateur",
      "Bizerte Nord",
      "Utique",
      "Jarzouna",
      "Ghezala",
    ],
  },
  {
    state: "Gabes",
    cities: [
      "Gabes Medina",
      "Gabes Sud",
      "Mareth",
      "El Hamma",
      "Ghannouche",
      "Nouvelle Matmata",
      "El Metouia",
      "Menzel Habib",
      "Matmata",
      "Gabes Ouest",
    ],
  },
  {
    state: "Gafsa",
    cities: [
      "Redeyef",
      "El Mdhilla",
      "Gafsa Sud",
      "Sned",
      "El Ksar",
      "El Guettar",
      "Metlaoui",
      "Sidi Aich",
      "Gafsa Nord",
      "Moulares",
      "Belkhir",
    ],
  },
  {
    state: "Jendouba",
    cities: [
      "Fernana",
      "Balta Bou Aouene",
      "Ain Draham",
      "Oued Mliz",
      "Tabarka",
      "Jendouba Nord",
      "Ghardimaou",
      "Bou Salem",
      "Jendouba",
    ],
  },
  {
    state: "Kairouan",
    cities: [
      "Kairouan Sud",
      "Oueslatia",
      "Sbikha",
      "Bou Hajla",
      "Nasrallah",
      "Haffouz",
      "Kairouan Nord",
      "Hajeb El Ayoun",
      "Chebika",
      "El Ala",
      "Cherarda",
    ],
  },
  {
    state: "Kasserine",
    cities: [
      "Feriana",
      "Sbiba",
      "Kasserine Sud",
      "El Ayoun",
      "Ezzouhour  (Kasserine)",
      "Mejel Bel Abbes",
      "Hassi El Frid",
      "Thala",
      "Kasserine Nord",
      "Sbeitla",
      "Jediliane",
      "Foussana",
      "Haidra",
    ],
  },
  {
    state: "Kebili",
    cities: ["El Faouar", "Kebili Nord", "Douz", "Kebili Sud", "Souk El Ahad"],
  },
  {
    state: "Kef",
    cities: [
      "Dahmani",
      "Nebeur",
      "Le Kef Ouest",
      "Kalaat Sinane",
      "Tajerouine",
      "Sakiet Sidi Youssef",
      "Touiref",
      "El Ksour",
      "Kalaa El Khasba",
      "Jerissa",
      "Le Sers",
      "Le Kef Est",
    ],
  },
  {
    state: "Mahdia",
    cities: [
      "Souassi",
      "Ouled Chamakh",
      "El Jem",
      "La Chebba",
      "Bou Merdes",
      "Sidi Alouene",
      "Chorbane",
      "Hbira",
      "Melloulech",
      "Ksour Essaf",
      "Mahdia",
    ],
  },
  {
    state: "Mannouba",
    cities: [
      "Oued Ellil",
      "Jedaida",
      "Douar Hicher",
      "El Battan",
      "Borj El Amri",
      "Mornaguia",
      "Mannouba",
      "Tebourba",
    ],
  },
  {
    state: "Medenine",
    cities: [
      "Zarzis",
      "Medenine Sud",
      "Midoun",
      "Ben Guerdane",
      "Medenine Nord",
      "Houmet Essouk",
      "Beni Khedache",
      "Ajim",
      "Sidi Makhlouf",
    ],
  },
  {
    state: "Monastir",
    cities: [
      "Ouerdanine",
      "Sayada Lamta Bou Hajar",
      "Ksar Helal",
      "Sahline",
      "Zeramdine",
      "Ksibet El Mediouni",
      "Beni Hassen",
      "Bekalta",
      "Jemmal",
      "Teboulba",
      "Bembla",
      "Moknine",
      "Monastir",
    ],
  },
  {
    state: "Nabeul",
    cities: [
      "Menzel Bouzelfa",
      "El Haouaria",
      "Hammamet",
      "Menzel Temime",
      "Grombalia",
      "Hammam El Ghezaz",
      "Nabeul",
      "Beni Khalled",
      "Korba",
      "Bou Argoub",
      "Takelsa",
      "Kelibia",
      "Beni Khiar",
      "Dar Chaabane Elfehri",
      "Soliman",
      "El Mida",
    ],
  },
  {
    state: "Sfax",
    cities: [
      "Sakiet Eddaier",
      "Sakiet Ezzit",
      "Sfax Est",
      "Sfax Sud",
      "Mahras",
      "Agareb",
      "Ghraiba",
      "Kerkenah",
      "Menzel Chaker",
      "Bir Ali Ben Khelifa",
      "Jebeniana",
      "El Amra",
      "Sfax Ville",
      "Esskhira",
      "El Hencha",
    ],
  },
  {
    state: "Sidi Bouzid",
    cities: [
      "Sidi Bouzid Ouest",
      "Ben Oun",
      "Ouled Haffouz",
      "Jilma",
      "Cebbala",
      "Mezzouna",
      "Regueb",
      "Menzel Bouzaiene",
      "Souk Jedid",
      "Bir El Haffey",
      "Sidi Bouzid Est",
      "Maknassy",
    ],
  },
  {
    state: "Siliana",
    cities: [
      "Gaafour",
      "Makthar",
      "Kesra",
      "Sidi Bou Rouis",
      "Le Krib",
      "Siliana Sud",
      "El Aroussa",
      "Rohia",
      "Siliana Nord",
      "Bou Arada",
      "Bargou",
    ],
  },
  {
    state: "Sousse",
    cities: [
      "Bou Ficha",
      "Kalaa Essghira",
      "Sousse Jaouhara",
      "Msaken",
      "Sousse Riadh",
      "Sousse Ville",
      "Enfidha",
      "Kalaa El Kebira",
      "Hammam Sousse",
      "Hergla",
      "Sidi El Heni",
      "Akouda",
      "Kondar",
      "Sidi Bou Ali",
    ],
  },
  {
    state: "Tataouine",
    cities: [
      "Tataouine Sud",
      "Tataouine Nord",
      "Smar",
      "Ghomrassen",
      "Bir Lahmar",
      "Dhehiba",
      "Remada",
    ],
  },
  {
    state: "Tozeur",
    cities: ["Degueche", "Tozeur", "Tameghza", "Hezoua", "Nefta"],
  },
  {
    state: "Tunis",
    cities: [
      "Ezzouhour  (Tunis)",
      "El Hrairia",
      "El Kram",
      "Sidi Hassine",
      "El Kabbaria",
      "Carthage",
      "El Ouerdia",
      "Ettahrir",
      "Bab Bhar",
      "La Marsa",
      "Le Bardo",
      "La Medina",
      "Cite El Khadra",
      "Essijoumi",
      "La Goulette",
      "Jebel Jelloud",
      "Bab Souika",
      "El Menzah",
      "El Omrane",
      "El Omrane Superieur",
      "Sidi El Bechir",
    ],
  },
  {
    state: "Zaghouan",
    cities: [
      "El Fahs",
      "Hammam Zriba",
      "Bir Mcherga",
      "Ennadhour",
      "Saouef",
      "Zaghouan",
    ],
  },
];
